version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: habitrush-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'habitrush_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3307:3306'
    volumes:
      - ./habitRush_mysql.sql:/docker-entrypoint-initdb.d/init.sql
